---
name: reviewdog
on:  # yamllint disable-line rule:truthy
  push:

jobs:

  yamllint:
    name: runner / yamllint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
      - name: yamllint
        uses: reviewdog/action-yamllint@v1.2
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-check

  misspell:
    name: runner / misspell
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: reviewdog/action-misspell@v1.6
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-check

  languagetool:
    name: runner / languagetool
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: reviewdog/action-languagetool@v1.4
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-check
          patterns: |
            **/*.md
          language: en
