---
name: reviewdog
on:  # yamllint disable-line rule:truthy
  push:

jobs:

  hadolint:
    name: runner / hadolint
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2.3.4
      - name: hadolint
        uses: reviewdog/action-hadolint@v1.25
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-check

  yamllint:
    name: runner / yamllint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
      - name: yamllint
        uses: reviewdog/action-yamllint@v1.2
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-check

  eslint:
    name: runner / eslint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
      - name: eslint
        uses: reviewdog/action-eslint@v1.12
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-check

  misspell:
    name: runner / misspell
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: reviewdog/action-misspell@v1.7
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-check

  languagetool:
    name: runner / languagetool
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: reviewdog/action-languagetool@v1.5
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-check
          patterns: |
            **/*.md
          language: en
